---
- name: System updates
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install Asterisk 18 LTS Dependencies
  apt: 
    name: "{{ dependencies_asterisk }}"
    state: latest
    update_cache: yes 

- name: Download and Install Asterisk 18 LTS
  include_tasks: download_asterisk.yaml

########################################################################

#- name: Create Asterisk User and Start Asterisk
#  include_tasks: deploy_user_asterisk.yaml

#- name: Install FreePBX 16 on Debian 11 / Debian 10
#  include_tasks: deploy_freepbx.yaml

#- name: Install FreePBX 16 on Debian 11 / Debian 10
#  include_tasks: install_freepbx.yaml